########## Application ##########
server:
  port: 19999
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true
    context-path: /api/devops
########## Spring ##########
spring:
  application:
    name: jj-devops
  banner:
    charset: UTF-8
  profiles:
    active: dev
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  threads:
    virtual:
      enabled: true
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
############## Sa-Token ##############
sa-token:
  token-name: Authorization
  timeout: 3600
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: random-64
  is-log: true
  token-prefix: Bearer

