spring:
  # 数据源配置
  datasource:
    username: root
    password: W&l1203@
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.156.24:3306/devops?characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
  # Redis 配置
  data:
    redis:
      host: 192.168.156.24
      port: 6379
      password: W&l1203@
      database: 0
      timeout: 30000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 0
        shutdown-timeout: 100
# Swagger 配置
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: @project.package@.controller
  show-actuator: true